config/routes.rb
Rails.application.routes.draw do
  # get '/tasks', to: 'tasks#index'
  # get '/tasks/new', to: 'tasks#new'
  # post '/tasks', to: 'tasks#create'
  # get '/tasks/:id', to: 'tasks#show', as: 'task'
  # get '/tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
  # patch '/tasks/:id', to: 'tasks#update'
  # delete '/tasks/:id', to: 'tasks#destroy'
  root to: 'tasks#index'
  resources :users, only: %i[new create]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :tasks do
    resources :status, only: %i[update]
    resources :comments, only: %i[create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  has_many_attached :avatars
  belongs_to :attachable, polymorphic: true, optional: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  enum state: %w[open in_progress done]
  belongs_to :user, foreign_key: :assignee_id
  has_many :comments, dependent: :destroy
  has_one :attachment, as: :attachable, dependent: :destroy
  accepts_nested_attributes_for :attachment, allow_destroy: true

  before_validation :assign_description, unless: :description_present

  validates :description, presence: true

  def assign_description
    self.description = 'No task description provided!'
  end

  def description_present
    description.present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :tasks, dependent: :destroy, foreign_key: :assignee_id
  has_many :comments, dependent: :destroy

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def ensure_user_logged_in
    return if logged_in?

    flash[:danger] = 'Please Log In to view the Tasks.'
    redirect_to login_path
  end

  def logged_in?
    current_user.present?
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_not_authorized
    flash[:warning] = 'All accessable tasks are listed below.'
    redirect_to root_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :current_user
  before_action :fetch_task

  def create
    @comment = @task.comments.create(comment_params)
    @comment.user_id = current_user.id

    redirect_to @task if @comment.save
  end

  private

  def fetch_task
    @task = Task.find(params[:task_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  protect_from_forgery with: :exception

  def new
    render component: 'Login'
  end

  # def create
  #   user = User.find_by(email: params[:login][:email].downcase)

  #   if user&.authenticate(params[:login][:password])
  #     session[:user_id] = user.id.to_s
  #     flash[:notice] = 'Successfully logged in!'
  #     redirect_to root_path
  #   else
  #     flash.now[:alert] = 'Incorrect credentials, try again!'
  #     render :new
  #   end
  # end
  def create
    user = User.find_by(email: params[:email].downcase)
 
    if user&.authenticate(params[:password])
      session[:user_id] = user.id.to_s
      flash[:notice] = 'Successfully logged in!'
      render json: { verified: 'true' }
    else
      flash.now[:alert] = 'Incorrect credentials, try again.'
      render json: { verified: 'false' }
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'Logged Out!'
    redirect_to login_path
  end
end

app/controllers/status_controller.rb
class StatusController < ApplicationController
  def update
    @task = Task.find(params[:id])
    @task.state = params[:state]
    if @task.save
      respond_to do |format|
        format.js { render 'update' }
      end
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :ensure_user_logged_in

  def index
    @tasks = TaskPolicy::Scope.new(current_user, Task).resolve
    # @tasks = policy_scope(Task)
    # alternatively: @tasks = policy_scope(Task)
  end

  def new
    @task = Task.new
  end

  def create
    @user = User.find(task_params[:assignee_id])
    @task = Task.new(task_params)
    authorize @task
    @task.creator_id = @current_user.id
    if @task.valid?
      @task.save
      redirect_to task_url(@task)
    else
      render 'new' # Renders the new page when task is not saved to the DB.
    end
  end

  def show
    @task = Task.find(params[:id])
    authorize @task
    @comments = @task.comments
  end

  def edit
    @task = Task.find(params[:id])
    authorize @task
  end

  def update
    @task = Task.find(params[:id])
    authorize @task

    redirect_to @task if @task.update_attributes(task_params)
  end

  def destroy
    task = Task.find(params[:id])
    authorize @task
    task.destroy
    redirect_to tasks_url
  end

  private

  def task_params
    params.require(:task)
          .permit(:description,
                  :assignee_id,
                  attachment_attributes: [avatars: []])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = 'Account created successfully!'
      redirect_to root_path
    else
      flash.now[:alert] = @user.errors.full_messages.join(', ')
      render :new
    end
  end

  private

  def user_params
    params.require(:user)
          .permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for ([@task, @task.comments.new]) do |f| %>
  <br />
  <%= f.label :content, "Add Comment" %>
  <br />
  <%= f.text_area :content %>
  <br />
  <%= f.submit "Submit" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Granite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

    <div id = "container">
      <% if @current_user %>
        Hi <%= @current_user.name %>
        <br />
        <%= link_to "Logout", logout_path, method: :delete, class: 'btn btn-primary btn-sm' %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/status/update.js.erb
$('#state').html(<strong><%= @task.state %></strong>);

app/views/tasks/edit.html.erb
<div>
  <h3>Enter new details: </h3>
  <%= form_for(@task) do |f| %>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <%= f.submit "Update Task" %>
  <% end %>
</div>

app/views/tasks/index.html.erb
<h1>Tasks List</h1>

<%= link_to 'Add new task', new_task_path, class: 'badge badge-primary' %>
<hr />
<% @tasks.each do |task| %>
  <%= link_to "#{task.description}", task_path(task), class: 'badge badge-info' %>
  <%= button_to 'Delete', task, :method => :delete, class: 'btn btn-danger btn-sm' %>
  <br />
<% end %>

app/views/tasks/new.html.erb
<div>
  <% if @task.errors.any? %>
    <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <h3>Add new Task</h3>
  <%= form_for(@task) do |f| %>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <%= collection_select(:task, :assignee_id, User.all, :id, :name) %>

    <%= f.fields_for :attachment, @task.build_attachment do |ff| %>
      <%= ff.file_field :avatars, multiple: true %>
    <% end %>

    <br />
    <%= f.submit "Create Task" %>
  <% end %>
</div>

app/views/tasks/show.html.erb
<div>
  <h2>
    You just created a new task!
  </h2>
  <h3>
    <%= @task.id %>)
    <%= @task.description %>

    <% if @task.attachment != nil %>
      <% @task.attachment.avatars.each do |attachment| %>
        <%= link_to attachment.filename %>
        <%= link_to 'download', rails_blob_path(attachment, disposition: "attachment") %>
        <br />
      <% end %>
    <% end %>

  </h3>

  Current Task State :
  <span id="state">
      <strong><%= @task.state %></strong>
  </span>
  <br />
  <br />
  Change the state of Task:
  <%= button_to "open", task_status_url({ task_id: @task.id, state: "open" }), remote: true, date: { type: 'script' }, method: :patch %>
  <%= button_to "in progress", task_status_url({ task_id: @task.id, state: "in_progress" }), remote: true, date:{ type: 'script' }, method: :patch %>
  <%= button_to "Done", task_status_url({ task_id: @task.id, state: "done" }), remote: true, date: { type: 'script' }, method: :patch %>

  <%= link_to 'Edit', edit_task_path(@task) %>
</div>

<div>
  <h2><strong>Comments</strong></h2>
    <% @comments.each do |comment| %>
      <h3>
        <%= comment.content %>
      </h3>
      <%= time_ago_in_words(comment.created_at) %><span> ago</span>
      <br />
    <% end %>
  <%= render 'comments/form' %>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>
      <div>
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true,class: 'form-control' %>
      </div>
      
      <div>
        <%= f.label :email %>
        <%= f.text_field :email,class: 'form-control' %>
      </div>
    
      <div>
        <%= f.label :password %>
        <%= f.password_field :password ,class: 'form-control'%>
      </div>
    
      <div>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation,class: 'form-control' %>
      </div>
    
      <br>
      
      <div>
        <%= f.submit "Sign up!" ,class:"btn btn-primary"%>
      </div>
    <% end %>
  </div>
</div>